name: Scan

on:
  pull_request:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: docker build . -t ${{ github.sha }}
    - uses: Azure/container-scan@v0
      with:
        image-name: ${{ github.sha }}
        severity-threshold: CRITICAL
      env:
        TRIVY_IGNORE_UNFIXED: true
